### ISSUE TITLE
Arduino Mega

### ISSUE THREAD

**Issue by mataide** [mikaelpatel/Arduino-SPI#2]
I am trying to use your library to let me extend my SRAM on Arduino Mega.

I am using this wire configuration with 23LC1024:

https://www.dropbox.com/s/lmacvq9q74d72mb/Captura%20de%20tela%202017-10-18%2012.34.44.png?dl=0

23LC1024              -> Arduino Mega
1 CS (Chip Select) -> D53
2 SO (Slave Out)   -> D50 (MOSI)
4 Vss (Ground)      -> Ground
5 SI (Slave In)        -> D51 (MISO)
6 SCK (Clock)        -> D52 (Clock)

I am using the example: Arduino-Storage -> Stream

And I changed it to:

```
#include "Storage.h"
#include "GPIO.h"
#include "SPI.h"
#include "MC23LCXXX.h"

#define USE_SOFTWARE_SPI
//#define USE_HARDWARE_SPI

#if defined(USE_SOFTWARE_SPI)
#include "Software/SPI.h"
Software::SPI<BOARD::D51, BOARD::D50, BOARD::D52> spi;
#elif defined(USE_HARDWARE_SPI)
#include "Hardware/SPI.h"
Hardware::SPI spi;
#endif

// External memory storage
MC23LC1024<BOARD::D53> sram(spi);
```

But with or without the 23LC1024 is attached to the arduino. For me shows the same SRAM Size:

```
sram.SIZE = 131072
sram.room = 111072
```

am I doing something wrong? Thanks

**Comment by mikaelpatel** [comment]
@mataide Thanks for your interest in this project. If I understand you correctly you are assuming that the library can detect if a device is present? Is that what you are looking for? The size is provided by the class constructor. There is no check that a device is present. Obviously this could be done by for instance reading and writing the first and last byte.

**Comment by mataide** [comment]
Thanks Mikael, but you missunderstood what I am asking for.

I dont know if my external SRAM is working, probably not. Because with the 23LC1024 connected, your library says that I have `sram.SIZE = 131072` and if I remove the 23LC1024 I still have the same amount of SRAM  `sram.SIZE = 131072`.

So what I am trying to do is trying to make sure that the external SRAM is working.

What I need is:

I need to stream a very big JSON with a library called https://github.com/bblanchon/ArduinoJson, however the default SRAM from Arduino Mega isnt enough.

So I just bought the SRAM 23LC1024 to expand the Arduino SRAM and parse the JSON.

**Comment by mikaelpatel** [comment]
@mataide To make sure that you have connected the SPI SRAM correctly you can use the benchmark sketch or read and write some bytes on the memory. 

Please remember that the SPI SRAM does not automatically increase the SRAM on the MPU. That is something very different. You must write code to transfer the data from MPU SRAM to SPI SRAM. 

Good luck with your project.

**Comment by mataide** [comment]
@mikaelpatel Thanks,

Can you provide an example of Output in Arduino Monitor that I can have sure that my external memory is working?

Also I should use USE_SOFTWARE_SPI? Because for Mega I am using:
Software::SPI<BOARD::D51, BOARD::D50, BOARD::D52> spi;

Best Regards,

**Comment by mikaelpatel** [comment]
@mataide If you run the benchmark example https://github.com/mikaelpatel/Arduino-Storage/blob/master/examples/Benchmarks/MC23LCXXX/MC23LCXXX.ino it will verify that the read/write was correct. It will also give the performance. With USE_SOFTWARE_SPI:
```
spi.FREQ(MHz) = 8
sram.SIZE(kbyte) = 128

write(N, us, us/byte, kbyte/s)
1, 84, 84.00, 11.90
10, 196, 19.60, 51.02
100, 1360, 13.60, 73.53
1000, 13020, 13.02, 76.80

read(N, us, us/byte, kbyte/s)
1, 84, 84.00, 11.90
10, 204, 20.40, 49.02
100, 1348, 13.48, 74.18
1000, 12840, 12.84, 77.88
```
And with Hardware::SPI
```
spi.FREQ(MHz) = 8
sram.SIZE(kbyte) = 128

write(N, us, us/byte, kbyte/s)
1, 24, 24.00, 41.67
10, 40, 4.00, 250.00
100, 168, 1.68, 595.24
1000, 1468, 1.47, 681.20

read(N, us, us/byte, kbyte/s)
1, 24, 24.00, 41.67
10, 40, 4.00, 250.00
100, 156, 1.56, 641.03
1000, 1352, 1.35, 739.64
```
During the read the values are checked against what was written. You get a message if that fails:
https://github.com/mikaelpatel/Arduino-Storage/blob/master/examples/Benchmarks/MC23LCXXX/MC23LCXXX.ino#L83

**Comment by mikaelpatel** [comment]
@mataide I am closing this issue as it is not really a bug report or feature request.
